apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: oc6ayy0v0-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/oc6ayy0v0-java-springboot-gitops